/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface Variables {
  knownVariables: KnownVariables;
  validationResult: ValidationResult[];
  variablesActionArgs: VariablesActionArgs;
  variablesData: VariablesData;
  variablesEditorDataContext: VariablesEditorDataContext;
  variablesSaveDataArgs: VariablesSaveDataArgs;
  void: Void;
  [k: string]: unknown;
}
export interface KnownVariables {
  children: KnownVariables[];
  description: string;
  metaData: MetaData;
  name: string;
  namespace: string;
  value: string;
}
export interface MetaData {
  type: string;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
export interface VariablesActionArgs {
  actionId: "openUrl";
  context: VariablesEditorDataContext;
  payload: string;
}
export interface VariablesEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface VariablesData {
  context: VariablesEditorDataContext;
  data: string;
  helpUrl: string;
}
export interface VariablesSaveDataArgs {
  context: VariablesEditorDataContext;
  data: string;
}
export interface Void {}
