/* eslint-disable */
// prettier-ignore
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Severity = ("INFO" | "WARNING" | "ERROR")

export interface Variables {
  projectVarNode: ProjectVarNode;
  validationResult: ValidationResult[];
  variablesData: VariablesData;
  variablesEditorDataContext: VariablesEditorDataContext;
  variablesSaveDataArgs: VariablesSaveDataArgs;
  void: Void;
  [k: string]: unknown;
}
export interface ProjectVarNode {
  children: ProjectVarNode[];
  description: string;
  key: string;
  name: string;
  type: string;
  value: string;
}
export interface ValidationResult {
  message: string;
  path: string;
  severity: Severity;
}
export interface VariablesData {
  context: VariablesEditorDataContext;
  data: string;
}
export interface VariablesEditorDataContext {
  app: string;
  file: string;
  pmv: string;
}
export interface VariablesSaveDataArgs {
  context: VariablesEditorDataContext;
  data: string;
}
export interface Void {}
